export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
// export const FETCH = 'FETCH'
export const ADD_TODO = 'ADD_TODO'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const MARK_TODO_AS_COMPLETED_REQUEST = 'MARK_TODO_AS_COMPLETED_REQUEST'
export const MARK_TODO_AS_COMPLETED_REQUEST_SUCCESS = 'MARK_TODO_AS_COMPLETED_REQUEST_SUCCESS'
export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const SET_NEW_TODO_TITLE_REQUEST = 'SET_NEW_TODO_TITLE_REQUEST'

// Album actions

export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const FETCH_ALBUMS_SUCCEEDED = 'FETCH_ALBUMS_SUCCEEDED';
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUMS_FAILED';
export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_SUCCEEDED = 'FETCH_PHOTOS_SUCCEEDED';
export const FETCH_PHOTOS_FAILED = 'FETCH_PHOTOS_FAILED';
export const RESET_ID = 'RESET_ID';
export const SET_PHOTO = 'SET_PHOTO';
export const SET_ALBUM_TITLE = 'SET_ALBUM_TITLE';
